server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: testapp
    password: testapp
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    url: jdbc:oracle:thin:@localhost:1521/xe
    user: testapp
    password: testapp

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh
    registration:
      path: /signup